app/views/blue_test.py
from flask import Blueprint, request, render_template, flash, redirect, url_for, send_from_directory, Response
from flask_paginate import Pagination, get_page_parameter
import time
import datetime
import os

from app.models import Testdata, Factory, Device
from app.lib import start, blink_single, blink_all, blink_failed, blink_stop, turn_on_all, turn_off_all, kickout_all, indicator_r, indicator_g, indicator_b
from app.lib import watch_to_jump, watch_timeout, watch_to_blink
from app.lib import set_factorycode, set_devicecode, set_totalcount, set_running_state, set_fwversion, set_mcuversion, set_ble_strength_low, set_wifi_strength_low
from app.lib import get_errno, set_errno, get_running_state, get_factorycode, get_devicecode
from app.lib import testdatas_stage
from app.lib import viewfunclog
from app.lib import logger_app
from app.lib import gen_excel, empty_folder
from app.lib.myutils import write_json_to_file
from app.lib.mycmd import reset_all, broadcast
from app.lib.tools import set_sqlite_value3, get_sqlite_value3, set_sqlite_value2
from app.lib.cloudhandler import check_gecloud_connection, upload_to_cloud
from app.lib.execmodel import update_testdatas_fcode, update_testdatas_devicecode, update_testdatas_bool_qualified_overall

from app.myglobals import topdir, gofolder


blue_test = Blueprint('blue_test', __name__, url_prefix='/test')


@blue_test.route('/error')
@viewfunclog
def vf_error():
    errno = request.args.get('errno')
    return render_template('test_error.html', errno=errno)

@blue_test.route('/config')
@viewfunclog
def vf_config():
    return render_template('test_config.html')

@blue_test.route('/tips_mcu')
@viewfunclog
def vf_tips_mcu():
    return render_template('tips_test_mcu.html')


@blue_test.route('/start')
@viewfunclog
def vf_start():
    msg = request.args.get('msg', '')
    return render_template('test_start.html', msg=msg)

@blue_test.route('/running')
@viewfunclog
def vf_running():
    return render_template('test_running.html')

@blue_test.route('/finished')
@viewfunclog
def vf_finished():
    results = Testdata.query.all()
    control_index = request.args.get('control_index')
    # pagination code
    # PER_PAGE = 30
    # page = request.args.get(get_page_parameter(), type=int, default=1) #获取页码，默认为第一页
    # start = (page-1)*PER_PAGE
    # end = page * PER_PAGE if len(results) > page * PER_PAGE else len(results)
    # pagination = Pagination(page=page, total=len(results), per_page=PER_PAGE, bs_version=3)
    # ret = Testdata.query.slice(start, end)
    # return render_template('testing.html', pagination=pagination, results=ret)
    return render_template('test_finished.html', results=results, control_index=control_index)

@blue_test.route('/logmonitor')
@viewfunclog
def vf_logmonitor():
    return render_template('test_logmonitor.html')

@blue_test.route('/reset')
@viewfunclog
def vf_reset():
    return render_template('test_reset.html')

# button & command

@blue_test.route('/cmd_broadcast', methods=['POST'])
@viewfunclog
def cmd_broadcast():
    logger_app.warn('click broadcast button')
    errno = broadcast()
    if errno == 0:
        msg = 'Broadcast done'
    else:
        msg = 'Boradcast error'
    return redirect(url_for('blue_test.vf_start', msg=msg))

@blue_test.route('/pre_cmd_start', methods=['POST'])
@viewfunclog
def pre_cmd_start():
    logger_app.warn('click start button')

    mode = request.form.get('mode', type=str)
    set_sqlite_value3('r_test_mode', mode)
    set_running_state()

    # gecloud_online = check_gecloud_connection()
    # if mode == 'production' and not gecloud_online:
    #     logger_app.warn('production mode start, but gecloud is not reachable')
    #     errno = 21
    #     set_errno(errno)
    #     return redirect(url_for('blue_test.vf_error', errno=errno))

    return redirect(url_for('blue_test.cmd_start')) 

@blue_test.route('/cmd_start', methods=['POST', 'GET'])
@viewfunclog
def cmd_start():
    start()
    watch_to_blink()
    watch_timeout()
    watch_to_jump()
    return redirect(url_for('blue_test.vf_running')) 

@blue_test.route('/post_cmd_start')
@viewfunclog
def post_cmd_start():
    fcode = get_factorycode()
    devicecode = get_devicecode()
    running = get_running_state()
    test_mode = get_sqlite_value3('r_test_mode')

    # 1. return if still running
    if running:
        return redirect(url_for('blue_test.vf_running'))

    # 2. adjust datas in testdatas table
    # update_testdatas_fcode(fcode)
    # update_testdatas_devicecode(devicecode)
    update_testdatas_bool_qualified_overall()

    # 3. production related actions
    if test_mode == 'production':
        # 3.1 stage testdata
        testdatas_stage()
        # 3.2 upload
        try:
            pass
            # upload_to_cloud()
        except Exception as e:
            logger_app.error('[upload] {}'.format(str(e)))

    errno = get_errno()
    if errno == 0:
        return redirect(url_for('blue_test.vf_finished'))
    else:
        return redirect(url_for('blue_test.vf_error', errno=errno))


@blue_test.route('/cmd_saveconfig', methods=['POST'])
@viewfunclog
def vf_cmd_saveconfig():
    # factorycode = request.form.get('factorycode')
    devicecode = request.form.get('devicecode', type=int)
    totalcount = request.form.get('totalcount', type=int)
    fwversion = request.form.get('fwversion', type=str)
    mcuversion = request.form.get('mcuversion', type=str)
    ble_strength_low = request.form.get('ble_strength_low', type=int)
    wifi_strength_low = request.form.get('wifi_strength_low', type=int)
    wifi_mac_low = request.form.get('wifi_mac_low', type=str) or '000000000000'
    wifi_mac_high = request.form.get('wifi_mac_high', type=str) or '000000000000'
    ble_mac_low = request.form.get('ble_mac_low', type=str) or '000000000000'
    ble_mac_high = request.form.get('ble_mac_high', type=str) or '000000000000'
    factory_stream_id = request.form.get('factory_stream_id', type=int) or 0
    # print('==wifi_mac_low==', wifi_mac_low)
    # print('==wifi_mac_high', wifi_mac_high)
    # print('==ble_mac_low==', ble_mac_low)
    # print('==ble_mac_high==', ble_mac_high)
    if len(mcuversion) == 0:
        mcuversion = '0'
    if ble_strength_low is None:
        ble_strength_low = -100
    if wifi_strength_low is None:
        wifi_strength_low = -110
    set_devicecode(devicecode) 
    set_totalcount(totalcount) 
    set_fwversion(fwversion)
    set_mcuversion(mcuversion)
    set_ble_strength_low(ble_strength_low)
    set_wifi_strength_low(wifi_strength_low)
    set_sqlite_value3('r_wifi_mac_low', wifi_mac_low)
    set_sqlite_value3('r_wifi_mac_high', wifi_mac_high)
    set_sqlite_value3('r_ble_mac_low', ble_mac_low)
    set_sqlite_value3('r_ble_mac_high', ble_mac_high)
    set_sqlite_value2('r_factory_stream_id', factory_stream_id)

    dict_params = {
        'devicecode': devicecode,
        'factory_stream_id': factory_stream_id,
        'totalcount': totalcount,
        'fwversion': fwversion,
        'mcuversion': mcuversion,
        'ble_strength_low': ble_strength_low,
        'wifi_strength_low': wifi_strength_low,
        'wifi_mac_low': wifi_mac_low,
        'wifi_mac_high': wifi_mac_high,
        'ble_mac_low': ble_mac_low,
        'ble_mac_high': ble_mac_high,
    }
    filename = os.path.join(gofolder, 'params.json')
    write_json_to_file(dict_params, filename)

    return redirect(url_for('blue_test.vf_start'))

@blue_test.route('/cmd_blink_single', methods=['POST'])
@viewfunclog
def vf_cmd_blink_single():
    logger_app.warn('click blink single button')
    mac = request.form.get('mac')
    index = request.form.get('index')
    blink_single(mac)
    return redirect(url_for('blue_test.vf_finished', control_index=index))

@blue_test.route('/cmd_blink_all', methods=['POST'])
@viewfunclog
def vf_cmd_blink_all():
    logger_app.warn('click blink all button')
    blink_all()
    return redirect(url_for('blue_test.vf_finished'))

@blue_test.route('/cmd_blink_failed', methods=['POST'])
@viewfunclog
def vf_cmd_blink_failed():
    logger_app.warn('click blink failed button')
    blink_failed()
    return redirect(url_for('blue_test.vf_finished'))

@blue_test.route('/cmd_blink_stop', methods=['POST'])
@viewfunclog
def vf_cmd_blink_stop():
    logger_app.warn('click blink stop button')
    blink_stop()
    return redirect(url_for('blue_test.vf_finished'))

@blue_test.route('/cmd_allon', methods=['POST'])
@viewfunclog
def cmd_allon():
    logger_app.warn('click turn on all button')
    turn_on_all()
    return redirect(url_for('blue_test.vf_finished'))

@blue_test.route('/cmd_alloff', methods=['POST'])
@viewfunclog
def cmd_alloff():
    logger_app.warn('click turn off all button')
    turn_off_all()
    return redirect(url_for('blue_test.vf_finished'))

@blue_test.route('/cmd_kickout', methods=['POST'])
@viewfunclog
def cmd_kickout():
    logger_app.warn('click kickout button')
    kickout_all()
    return redirect(url_for('blue_test.vf_finished'))

@blue_test.route('/cmd_download_testdatas', methods=['POST'])
@viewfunclog
def cmd_download_testdatas():
    timestamp = datetime.datetime.now().strftime('%Y_%m_%d_%H_%M_%S')
    excelname = 'Testdata-' + timestamp + '.xls'
    excelfolder = os.path.join(topdir, 'pub', 'excel')
    filename = os.path.join(excelfolder, excelname)
    empty_folder(excelfolder)    
    gen_excel(Testdata, filename)
    # 普通下载
    # return send_from_directory(excelfolder, excelname, as_attachment=True)
    # 流式读取
    def send_file():
        with open(filename, 'rb') as filestream:
            while True:
                data = filestream.read(1024*1024) # 每次读取1M大小
                if not data:
                    break
                yield data
    response = Response(send_file(), content_type='application/octet-stream')
    response.headers["Content-disposition"] = 'attachment; filename=%s' % excelname
    return response


@blue_test.route('/cmd_indicator_r', methods=['POST'])
@viewfunclog
def cmd_indicator_r():

app/views/database.py
from flask import Blueprint, request, render_template, flash, redirect, url_for
from flask_paginate import Pagination, get_page_parameter
import datetime

from app.models import db, tb_device_type, tb_factory, tb_data_aging
from app.models import view_data_aging

# create_view and delete_view is actually two pymysql execute function
# not that like typical models, such as db
from app.lib import create_view, delete_view

blue_database = Blueprint('blue_database', __name__)

# 1. view functions definition

@blue_database.route('/info_aging/', methods=['GET'])
def info_aging():
    # results = tb_data_aging.query.all()
    results = view_data_aging.query.all()
    control_index = request.args.get('control_index')

    # pagination code
    PER_PAGE = 30
    page = request.args.get(get_page_parameter(), type=int, default=1) #获取页码，默认为第一页
    start = (page-1)*PER_PAGE
    end = page * PER_PAGE if len(results) > page * PER_PAGE else len(results)
    pagination = Pagination(page=page, total=len(results), per_page=PER_PAGE, bs_version=3)
    ret = view_data_aging.query.slice(start, end)

    return render_template('manageaging.html', pagination=pagination, results=ret, control_index=control_index)


@blue_database.route('/info_device/', methods=['GET'])
def info_device():
    results = tb_device_type.query.all()
    return render_template('managedevice.html', results=results)

@blue_database.route('/info_factory/', methods=['GET'])
def info_factory():
    results = tb_factory.query.all()
    return render_template('managefactory.html', results=results)

flask/views/command.py
from flask import Blueprint, request, render_template, flash, redirect, url_for
from pipe_nonblock import Pipe

from lib import start, stop, turn_on_off, cleanup_temp, cleanup_stage, migrate_to_archive


blue_command = Blueprint('blue_command', __name__)


# pipe1_recv for stop()
pipe1_recv, pipe1_send = Pipe(duplex=False, conn1_nonblock=False, conn2_nonblock=False)
pipe2_recv, pipe2_send = Pipe(duplex=False, conn1_nonblock=True, conn2_nonblock=True)


@blue_command.route('/cmd_start/', methods=['POST'])
def cmd_start():
    # errno is None
    cleanup_temp()
    errno = start(pipe2_recv, pipe1_send)
    flash('Started!')
    # return redirect(url_for('blue_index.index'))
    return redirect(url_for('blue_database.info_aging', refresh=True))

@blue_command.route('/cmd_stop/', methods=['POST'])
def cmd_stop():
    print("[debug] press stop")
    errno = stop(pipe1_recv,pipe2_send)
    if 0 == errno:
        flash('Stopped!')
    else:
        flash('stop error')
    return redirect(url_for('blue_database.info_aging'))

@blue_command.route('/cmd_on_off/', methods=['POST'])
def cmd_on_off():
    mac = request.form.get('mac')
    on_off = request.form.get('on_off')
    print("[debug] press turn {} {}".format(on_off, mac))
    errno = turn_on_off(mac, on_off)
    flash('Turn {} {}'.format(on_off, mac))
    return redirect(url_for('blue_database.info_aging'))

app/templates/_configinfo.html
    <div style="display: inline">
        <p style="display: inline"><strong>类型</strong>:</span> <span class="text-success"> {{ devicename() }} ({{ devicecode() }})</p>
        &nbsp;&nbsp;&nbsp;
        <p style="display: inline"><strong>数量</strong>:</span> <span class="text-success"> {{ totalcount() }}</p>
        &nbsp;&nbsp;&nbsp;
        <p style="display: inline"><strong>固件版本</strong>:</span> <span class="text-success"> {{ fwversion() }}</p>
        &nbsp;&nbsp;&nbsp;
        <p style="display: inline"><strong>MCU版本</strong>:</span> <span class="text-success"> {{ mcuversion() }}</p>
        &nbsp;&nbsp;&nbsp;
        <p style="display: inline"><strong>BLE强度阈值</strong>:</span> <span class="text-success"> {{ ble_strength_low() }}</p>
        &nbsp;&nbsp;&nbsp;
        <p style="display: inline"><strong>WIFI强度阈值</strong>:</span> <span class="text-success"> {{ wifi_strength_low() }}</p>
        <br>
        <br>
        <p style="display: inline"><strong>wifi_mac_low</strong>:</span> <span class="text-success"> {{ wifi_mac_low() }}</p>
        &nbsp;&nbsp;&nbsp;
        <p style="display: inline"><strong>wifi_mac_high</strong>:</span> <span class="text-success"> {{ wifi_mac_high() }}</p>
        &nbsp;&nbsp;&nbsp;
        <p style="display: inline"><strong>ble_mac_low</strong>:</span> <span class="text-success"> {{ ble_mac_low() }}</p>
        &nbsp;&nbsp;&nbsp;
        <p style="display: inline"><strong>ble_mac_high</strong>:</span> <span class="text-success"> {{ ble_mac_high() }}</p>
        &nbsp;&nbsp;&nbsp;
        <p style="display: inline"><strong>factory_stream_id</strong>:</span> <span class="text-success"> {{ factory_stream_id() }}</p>
        &nbsp;&nbsp;&nbsp;
    </div>
    <hr>

app/templates/_db_query_aging.html
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<html>
<head>
  <title>
    Aging Test Tool
  </title>
</head>
<body>
<h4>查看测试数据</h4>
<div>
{{ pagination.info }}
{{ pagination.links }}
</div>
<div>
  <a href="{{ url_for('blue_database.info_aging') }}" class="btn btn-default">刷新</a>
</div>

  {%- for message in get_flashed_messages() %}
<div class="alert alert-dismissible alert-success">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong>{{ message }}</strong> 
</div>
  {% endfor %}

<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>#</th>
      <th>设备类型</th>
      <th>工厂</th>
      <th>固件版本</th>
      <th>RSSI_BLE</th>
      <th>RSSI_WIFI</th>
      <th>MAC_BLE</th>
      <th>MAC_WIFI</th>
      <th>合格</th>
      <th>云同步</th>
      <th>时间</th>
      <th colspan="2">控制</th>
    </tr>
  </thead>
  <tbody>
    {% for result in results %}
    {% if loop.index|string == control_index %}
    <tr class="active">
    {% elif not result.is_qualified %}
    <tr class="warning">
    {% else %}
    <tr class="info">
    {% endif %}
      <td>{{ loop.index + pagination.skip }}</td>
      <td>{{result.device_type}}</td>
      <td>{{result.factory}}</td>
      <td>{{result.fw_version}}</td>
      <td>{{result.rssi_ble}}</td>
      <td>{{result.rssi_wifi}}</td>
      <td>{{result.mac_ble}}</td>
      <td>{{result.mac_wifi}}</td>
      <td>{{result.is_qualified}}</td>
      <td>{{result.is_sync}}</td>
      <td>{{result.datetime}}</td>
      <td>
        <form action = "{{url_for('blue_command.cmd_on_off')}}" method = "post">
          <input type = "hidden" name = "index" value= {{loop.index + pagination.skip}} />
          <input type = "hidden" name = "mac" value="{{result.mac_ble}}" />
          <input type = "hidden" name = "on_off" value="on" />
          <button type="submit" >on</button>
        </form>
      </td>
      <td>
        <form action = "{{url_for('blue_command.cmd_on_off')}}" method = "post">
          <input type = "hidden" name = "index" value= {{loop.index+pagination.skip}} />
          <input type = "hidden" name = "mac" value="{{result.mac_ble}}" />
          <input type = "hidden" name = "on_off" value="off" />
          <button type="submit" >off</button>
        </form>
      </td>
    </tr>
    {% else %}
    {% endfor %}
  </tbody>
</table> 

  {%- for message in get_flashed_messages() %}
<div class="alert alert-dismissible alert-success">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong>{{ message }}</strong> 
</div>
  {% endfor %}

<div>
  <div>
{{ pagination.links }} 
  </div>
<div>
  <br>
  <br>
</body>
</html>

app/templates/_db_query_device.html
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
<html>
<head>
  <title>
    GE Lighting Aging Test Tool
  </title>
</head>
<body>
<h4>查看设备类型</h4>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>序号</th>
      <th>类型代码</th>
      <th>设备类型</th>
      <th>详细信息</th>
      <th>其他信息</th>
    </tr>
  </thead>
  <tbody>
    {% for result in results %}
    <tr>
      <td>{{ loop.index }}</td>
      <td>{{result.code}}</td>
      <td>{{result.type}}</td>
      <td>{{result.detail}}</td>
      <td>{{result.description}}</td>
    </tr>
    {% else %}
    {% endfor %}
  </tbody>
</table>


</body>
</html>

app/templates/_db_query_factory.html
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<html>
<head>
  <title>
    GE Lighting Aging Test Tool
  </title>
</head>
<body>
  <h4>查看厂家信息 </h4>
  <table class="table table-striped table-hover">
    <tr>
      <th>序号</th>
      <th>工厂代码</th>
      <th>工厂名称</th>
      <th>其他</th>
    </tr>
    {% for result in results %}
    <tr>
      <td>{{ loop.index }}</td>
      <td>{{result.id}}</td>
      <td>{{result.name}}</td>
      <td>{{result.description}}</td>
    </tr>
    {% else %}
    {% endfor %}
  </table>
</body>
</html>

app/templates/_resulttable.html
        <td>{{ result.device.name }}</td>
        <td>{{ result.factory.name }}</td>
        <td>{{ result.fw_version }}</td>
        <td>{{ result.rssi_ble1 }}</td>
        <td>{{ result.rssi_wifi1|parse_rssi_wifi_na }}</td>
        <td>{{ result.mac_ble }}</td>
        <td>{{ result.mac_wifi }}</td>
        <td>{{ result.reserve_str_1 }}</td>
        <!--<td {% if not result.bool_qualified_signal %}bgcolor="red"{% endif %} >{{ result.bool_qualified_signal|parse_is_qualified }}</td>-->
        <td {% if not result.bool_qualified_signal %} class="alert-warning" {% endif %} >{{ result.bool_qualified_signal|parse_is_qualified }}</td>
        <td {% if not result.bool_qualified_check %} class="alert-warning"{% endif %} >{{ result.bool_qualified_check|parse_is_qualified }}({{result.status_cmd_check1}})</td>
        <td {% if not result.bool_qualified_scan %} class="alert-warning" {% endif %} >{{ result.bool_qualified_scan|parse_is_qualified }}</td>
        <td {% if not result.bool_qualified_deviceid %} class="alert-warning" {% endif %} >{{ result.bool_qualified_deviceid|parse_is_qualified }}</td>
        <td {% if not result.reserve_bool_1 %} class="alert-warning" {% endif %} >{{ result.reserve_bool_1|parse_is_qualified }}</td>
        <td {% if result.reserve_int_1 != 0 %} class="alert-warning" {% endif %} >{{ result.reserve_int_1|parse_mac_is_qualified }}({{result.reserve_int_1}})</td>
        <td>{{ result.datetime }}</td>

app/templates/_thead.html
        <thead>
        <tr>
            <th rowspan="2">#</th>
            <th rowspan="2">设备类型</th>
            <th rowspan="2">厂家</th>
            <th rowspan="2">固件版本</th>
            <th rowspan="2">RSSI_BLE</th>
            <th rowspan="2">RSSI_WIFI</th>
            <th rowspan="2">MAC_BLE</th>
            <th rowspan="2">MAC_WIFI</th>
            <th rowspan="2">MCU</th>
            <th colspan="6">检测结果</th>
            <th rowspan="2">时间</th>
            <th rowspan="2">控制</th>
        </tr>
        <tr>
            <th>信号强度</th>
            <th>组合指令</th>
            <th>广播扫描</th>
            <th>设备类型</th>
            <th>版本检测</th>
            <th>MAC检测</th>
        </tr>
        </thead>

app/templates/about.html
{% extends '_mybase.html' %}

{% block indent_content %}

    <script src="{{ url_for('static',filename='js/jquery-1.12.4.min.js') }}"></script>
    <script type="text/javascript" charset="utf-8">
        $(document).ready(function () {
            $("#link_version").click(function(){
                var cmd = "git log --oneline -1";
                var url = location.protocol + '//' + document.domain + ':' + location.port + "{{ url_for('api_cmd_onlinecmd') }}" + "?cmd=" + cmd;
                $.post(
                    url,
                    function(data){
                        $('#p_gitlog').css('color', 'red');
                        $('#p_gitlog').html(data.output);
                    },
                    "json"
                );
            });
        });
    </script>


    <div style="width:50%">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">版本</h3>
            </div>
            <div class="panel-body">
                {# <a id="link_version" title="查看提交记录" href="#">version 1.5</a> #}
                <a id="link_version" title="查看提交记录" href="#">{{ get_version() }}</a>
                <br>
                <br>
                <p id="p_gitlog"></p>
            </div>
        </div>

        <!--
        <div class="panel panel-success">
          <div class="panel-heading">
            <h3 class="panel-title">联系</h3>
          </div>
          <div class="panel-body">
            <p>lingshan.kong@ge.com</p> 
            <p>nan2.li@ge.com</p>
          </div>
        </div>
        -->
    </div>
{% endblock %}

app/templates/admin_go.html
{% extends '_mybase.html' %}

{% block indent_content %}
    {{ super() }}

    <legend>Go程序管理 (admin only)</legend>

    <table border="1">
        <tr>
            <th>Index</th>
            <th>File</th>
            <th>Operation</th>
        </tr>
        {% for file in filelist %}
            <tr>
                <td>{{ loop.index }}</td>
                <td>&nbsp;{{ file }}&nbsp;</td>
                <td>
                    &nbsp;
                    <a href="{{ url_for('blue_admin.cmd_view_file', filename=file) }}">view</a>&nbsp;
                    <a href="{{ url_for('blue_admin.cmd_download_file', filename=file) }}">download</a>&nbsp; &nbsp;
                    <a href="{{ url_for('blue_admin.cmd_delete_file', filename=file) }}" style="color: orangered"
                       οnclick="{if(confirm('Delete confirmed?')){this.document.formname.submit();return true;}return false;}">delete</a>&nbsp;
                </td>
            </tr>
        {% else %}
        {% endfor %}
    </table>
    <a href="{{ url_for('blue_admin.vf_go') }}">refresh</a>

    <br>
    <br>
    <br>

    <legend>上传更新文件 (admin only)</legend>

    <form action={{ url_for('blue_admin.cmd_upload_file') }} method="post" enctype=multipart/form-data>
        <input type="file" name="file" value="请选择配置文件" style="display: inline">
        <input type="submit" value='导入'>
    </form>

    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
                <p class="text-warning">{{ message }}</p>
            {% endfor %}
        {% endif %}
    {% endwith %}

{% endblock %}

app/templates/manage_device.html
{% extends '_mybase.html' %}

{% block indent_content %}
    {{ super() }}

    <legend>查看设备类型</legend>
    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th>序号</th>
            <th>设备名称</th>
            <th>类型代码</th>
            <th>类型代码</th>
            <th>其他信息</th>
        </tr>
        </thead>
        <tbody>
        {% for result in get_devices() %}
            <tr>
                <td>{{ loop.index }}</td>
                <td>{{ result.name }}</td>
                <td>{{ result.code_hex }}</td>
                <td>{{ result.code }}</td>
                <td>{{ result.description }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

app/templates/manage_log.html
{% extends '_mybase.html' %}

{% block indent_content %}
    {{ super() }}

    <legend>查看日志</legend>

    <table border="1">
        <tr>
            <th>#</th>
            <th>日志</th>
            <th>操作</th>
        </tr>
        {% for file in filelist %}
            <tr>
                <td>&nbsp;{{ loop.index }}&nbsp;</td>
                <td>&nbsp;{{ file }}&nbsp;</td>
                <td>
                    &nbsp;
                    <a href="{{ url_for('blue_manage.cmd_view_log', filename=file) }}">查看</a>&nbsp;
                    <a href="{{ url_for('blue_manage.cmd_download_log', filename=file) }}">下载</a>&nbsp; &nbsp;
                    <a href="{{ url_for('blue_manage.cmd_delete_log', filename=file) }}" style="color: orangered" onClick="return confirm('确定删除吗?');">删除</a>&nbsp;
                </td>
            </tr>
        {% else %}
        {% endfor %}
    </table>

{% endblock %}

app/templates/test_error.html
{% extends '_mybase.html' %}

{% block indent_content %}
    {{ super() }}

    <div class="alert alert-dismissible alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <h4>测试失败({{ errno }})</h4>
       <p>{{ errinfo() }}</p>
        <p>请检查测试环境, <a href="{{ url_for('blue_test.vf_config') }}" class="alert-link">重新测试</a>.</p>
    </div>

{% endblock %}